# Generated by Django 5.1.1 on 2024-09-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projetos", "0002_alter_projeto_data_conclusao"),
    ]

    operations = [
        migrations.AddField(
            model_name="projeto",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="paginas/imagem/"),
        ),
    ]
