# Generated by Django 5.1.1 on 2024-09-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projetos", "0005_alter_projeto_imagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="projeto",
            name="link_projeto",
            field=models.CharField(default="http://exemplo.com", max_length=100),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
